### ISSUE TITLE
Cannot write using Gridfs model

### ISSUE THREAD

**Issue by vladoro** [lykmapipo/mongoose-gridfs#13]
node.js: "8.4.0"
mongoose: "4.12.1"
mongoose-gridfs: "0.2.0"
gridfs-stream: "1.1.1"
mongodb: "2.2.31"
mongodb-core: "2.1.15"

Cannot write to GridFs using Gridfs Model.

Exception:
```
node_modules/mongodb/lib/gridfs/grid_store.js:130
  this.readPreference = this.options.readPreference || db.options.readPreference || ReadPreference.PRIMARY;
                                                                 ^

TypeError: Cannot read property 'readPreference' of null
    at new GridStore (node_modules/mongodb/lib/gridfs/grid_store.js:130:66)
    at new GridWriteStream (node_modules/gridfs-stream/lib/writestream.js:64:16)
    at Grid.createWriteStream (node_modules/gridfs-stream/lib/index.js:42:10)
    at GridFSStorage.write (node_modules/mongoose-gridfs/lib/storage.js:127:40)
    at model.GridFSSchema.methods.write (node_modules/mongoose-gridfs/lib/schema.js:75:16)
    at Function.GridFSSchema.statics.write (node_modules/mongoose-gridfs/lib/schema.js:164:14)
    at Object.<anonymous> (index.js:17:6)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3


```

**Comment by vladoro** [comment]
See code to reproduce the issue:
[https://github.com/vladoro/mongoose-gridfs-issues-13]()

**Comment by CruizK** [comment]
Alright, after a couple minutes of digging down the rabbit hole, I've found that this is due to how mongoose works with gridfs, when you enable `useMongoClient:true` in options for connecting to mongoose. It has no options variable attached to the db, this causes the "cannot read property" error you're getting. A band aid solution for this is to change `useMongoClient:true` to `useMongoClient:false` or just don't use it in the options. I am however looking for a better solution, since it seems having `useMongoClient:true` is proper practice. I'll look more into the issue and see if i can find a better solution.

**Comment by CruizK** [comment]
ah, disregard my previous statement, I already fixed this in the GitHub repo, but it appears the npm package hasn't been updated with the repo. I believe the person who has to do this is the owner.

**Comment by lykmapipo** [comment]
@CruizK nmp updated with v0.3.0
