### ISSUE TITLE
Stream variant doesn't work

### ISSUE THREAD

**Issue by talha-asad** [lykmapipo/mongoose-gridfs#23]
`readById` works well with the callback version, that provides a buffer but the stream version just errors out and doesn't work. Does it work for you?

Below is the error I get:

```bash
TypeError: Cannot read property 'on' of undefined
      at GridReadStream.Readable.pipe (_stream_readable.js:585:7)
      at router.get (test/src/index.js:120:79)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

The id for the file seems to be correct.

**Comment by talha-asad** [comment]
It does, sorry I had it setup wrong.
