### ISSUE TITLE
Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by michwroch** [lykmapipo/mongoose-gridfs#56]
Hello, I'm using mongoose 5.9.15 with mongoose-gridfs1.2.47. After launch server on node.js I have error:

.../node_modules/mongodb/lib/gridfs-stream/index.js:50
    _chunksCollection: db.collection(options.bucketName + '.chunks'),
                          ^

TypeError: Cannot read property 'collection' of undefined
    at new GridFSBucket (.../node_modules/mongodb/lib/gridfs-stream/index.js:50:27)
    at createBucket (.../node_modules/mongoose-gridfs/lib/bucket.js:590:18)
    at createModel .../node_modules/mongoose-gridfs/lib/bucket.js:641:18)
    at Object.<anonymous> (.../db/general/index.js:27:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

What's happen? How I can resolve this problem?

**Comment by sacheen** [comment]
This error is due the mongo connection is not established before you execute createModel()
ensure that you have a connection before executing createModel()
