### ISSUE TITLE
Cannot read properties of undefined (reading 'prototype') since mongoose 6

### ISSUE THREAD

**Issue by PierreBrisorgueil** [lykmapipo/mongoose-gridfs#71]
```
/Users/pierrebrisorgueil/Documents/Dev/github/rype/Node/node_modules/mongoose-schema-jsonschema/index.js:20
  Types.Embedded.prototype.jsonSchema = types.mixed_jsonSchema;
                 ^
TypeError: Cannot read properties of undefined (reading 'prototype')
    at moduleFactory (/Users/pierrebrisorgueil/Documents/Dev/github/rype/Node/node_modules/mongoose-schema-jsonschema/index.js:20:18)
    at Object.<anonymous> (/Users/pierrebrisorgueil/Documents/Dev/github/rype/Node/node_modules/@lykmapipo/mongoose-common/index.js:71:38)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/pierrebrisorgueil/Documents/Dev/github/rype/Node/node_modules/mongoose-gridfs/lib/schema.js:6:41)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

Hello, we've been stuck on this since the mongoose 6 update, despite the mongoose common update 🤔 @lykmapipo

**Comment by PierreBrisorgueil** [comment]
perfect! thx @lykmapipo
