### ISSUE TITLE
hello?js eror

### ISSUE THREAD

**Issue by hughdev** [lykmapipo/mongoose-gridfs#72]
const { createModel } = require('mongoose-gridfs')
error
TypeError: Cannot read property 'Decimal128' of null
 at Object.<anonymous> (/Users/-check/node_modules/@lykmapipo/mongoose-common/node_modules/mongoose/lib/types/decimal128.js:13:44)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/-check/node_modules/@lykmapipo/mongoose-common/node_modules/mongoose/lib/utils.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/-check/node_modules/@lykmapipo/mongoose-common/lib/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

not ? not support require?????

**Comment by hughdev** [comment]
@lykmapipo hello.

**Comment by hughdev** [comment]
hello,this my project not surport es6 import function. so ,that so bad...
![image](https://user-images.githubusercontent.com/9314396/137681182-1c9af3dd-0554-433e-892f-a7909165f59e.png)
we must be lock version....
can u surport require function?
const { createModel } = require('mongoose-gridfs')

**Comment by hughdev** [comment]
![image](https://user-images.githubusercontent.com/9314396/137681429-b8d3f601-769f-4c71-9ad3-122f20d277a5.png)
It's too unfriendly. my project was crash.on line..
pls.
